Dev4w4n/e-masjid.my

- README.md
- api/pom.xml
Hi 😄 
In this PR I would like to perform build using build aggregator.
The build aggregator will build all maven modules in one go.
Please review and merge if you're happy!
Thanks.
XOXO
> Building all api at one go

- dashboard/Dockerfile
- public-web/Dockerfile
Before 
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS         PORTS
NAMES                       SIZE
9ccdff05c78b   e-masjidmy-public-web     "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes   0.0.0.0:3001->3000/tcp   e-masjidmy-public-web-1     **113MB (virtual 738MB)**
d94b016adfdf   e-masjidmy-dashboard      "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes   0.0.0.0:3000->3000/tcp   e-masjidmy-dashboard-1      **196MB (virtual 936MB)**
After
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS
NAMES                       SIZE
fe53738f820e   e-masjidmy-public-web     "docker-entrypoint.s…"   10 seconds ago   Up 7 seconds    0.0.0.0:3001->3000/tcp   e-masjidmy-public-web-1 …
> reduce image size for public-web and dashboard image

- dashboard/Dockerfile.dev
- docker-compose-v2.yaml
- public-web/.env
- public-web/Dockerfile.dev
- run-dev2.sh
Kalau run-dev.sh slow, try pakai run-dev2.sh
> Fix for slow run-dev

- dashboard/Dockerfile.dev
- public-web/Dockerfile.dev
Closes #28
aku termiss untuk dockerfile.dev
sebelum
e703f24a2e9e   e-masjidmy-public-web     "docker-entrypoint.s…"   14 seconds ago   Up 11 seconds   0.0.0.0:3001->3000/tcp   e-masjidmy-public-web-1     46B **(virtual 218MB)**
cbd78ea2278e   e-masjidmy-dashboard      "docker-entrypoint.s…"   14 seconds ago   Up 11 seconds   0.0.0.0:3000->3000/tcp   e-masjidmy-dashboard-1      46B **(virtual 219MB)**
selepas
66730a9ce65d   e-masjidmy-dashboard      "docker-entrypoint.s…"   9 seconds ago    Up 7 seconds   0.0.0.0:3000->3000/tcp   e-masjidmy-dashboard-1      46B **(virtual 155MB)**
3548f0feac6a   e-masjidmy-public-web     "docker-entrypoint.s…"   9 seconds ago    Up 7 seconds   0.0.0.0:3001->3000/tcp   e-masjidmy-public-web-1     46B **(virtual 154MB)**
> use alpine for both public-web and dashboard dockerfile.dev version

- dashboard/Dockerfile.dev
- public-web/Dockerfile.dev
Reverts Dev4w4n/e-masjid.my#42
@pojicode aku terpaksa revert benda ni sebab . Mac tak jalan node:20-alpine
Jangan marah. 
CC: @fazreil
> Revert "use alpine for both public-web and dashboard dockerfile.dev version"

- api/cadangan-api/Dockerfile
- api/khairat-api/Dockerfile
- api/tabung-api/Dockerfile
- dashboard/src/Config.js
- dashboard/src/views/khairat/carian/Carian.js
- public-web/src/Config.js
> Fix Senarai ahli khairat 

- dashboard/src/components/print/khairat/SenaraiAhli.js
- dashboard/src/components/print/tabung/DenominasiPrint.js
- dashboard/src/components/print/tabung/PenyataBulananPrint.js
- dashboard/src/constants/print.json
> adding footer on all reports

- dashboard/src/views/tetapan/TetapanMasjid.js
Fix spinner dan issue value assignment error due to value setting while page rendering.
> Tetapan Masjid : On page load, tambah spinner #61

- dashboard/src/views/khairat/carian/Carian.js
Dah add pagination at Khairat > Carian.
> Added pagination to Khairat > Carian

- dashboard/src/scss/_custom.scss
> Bug fix for issue #75 Khairat tag jadi pelik bila ada banyak tags

- dashboard/src/views/tabung/daftar/Daftar.js
- dashboard/src/views/tetapan/TetapanMasjid.js
Apply same changes from issue #65 to buttons in \tabung\daftar and tetapan.
> Apply same changes from issue #65 to other buttons

- dashboard/src/components/print/khairat/SenaraiAhli.js
- dashboard/src/components/print/tabung/DenominasiPrint.js
- dashboard/src/components/print/tabung/PenyataBulananPrint.js
- dashboard/src/service/tetapan/TetapanMasjidApi.js
> display nama masjid in report from tetapan api

- README.en.md
- README.md
Two readme files has been updated with latest minimum requirment for system development. English and Bahasa.
> README: Tambah maklumat Keperluan Sistem Minima #53

- .gitignore
- api/tabung-api/pom.xml
- public-web/package.json
- public-web/src/Pages/Cadangan.jsx
- public-web/src/components/Navbar.jsx
- public-web/src/constants/error.json
- public-web/src/service/Cadangan/CadanganApi.js
- handle network errors if related service is down dari perspective public web. For example public web up and other cadangan api and dashboard service down.
- add git ignore unruk intellij idea 
- add local profile (maven) untuk tabung api supaya boleh run tabung api independent locally
- add proxy ke http://localhost:3000 kat public web untuk avoid cors error 
- kat cadangan page handle email and phone validation incase if customer decide to enter email and phone, if empty we dont validate
- letak error message dalam constant file
> Handle network error when related microservice is down from public web and some validations for cadangan 

- dashboard/src/views/khairat/carian/Carian.js
> Set default page size to 25 , 50 , 100, 200 for issue #88.

- dashboard/src/views/khairat/carian/Carian.js
> Fixed paginationPerPage to 25.

- dashboard/src/scss/_custom.scss
- dashboard/src/views/cadangan/qr/Qr.js
> Adjustments on QR template editor to fix hidden HEX code textbox.

- public-web/src/components/Navbar.jsx
The login button move to the navbar instead of inside mobile menu
> Move the mobile login button to navbar

- dashboard/src/components/AppHeader.js
Updated bahan rujukan link in AppHeader.js to https://docs-e-masjid-my.pages.dev/
> Updated bahan rujukan link in AppHeader.js

- api/cadangan-api/controller/cadangan_controller.go
- api/cadangan-api/model/paginate.go
- api/cadangan-api/model/response.go
- api/cadangan-api/repository/cadangan_repository.go
- dashboard/src/components/cadangan/CadanganList.js
> Create pagination for Cadangan

- public-web/src/components/Home/Front.jsx
> Update Front.jsx for issues #159

- public-web/src/Pages/Home.jsx
- public-web/src/components/WaktuSolat/apiSolat.js
- public-web/src/components/WaktuSolat/senaraiZon.js
- public-web/src/components/WaktuSolat/waktuSolat.jsx
Penambahan panel asas untuk paparan waktu solat bagi masjid, mengikut tetapan zon yang telah dibuat.
> ADD : Panel Waktu Solat (Basic)

- docker-compose.yaml
- postgres/zz_dummy.sql
> chore: add seed data

- api/cadangan-api/controller/cadangan_controller.go
- api/cadangan-api/main.go
- api/cadangan-api/repository/cadangan_repository.go
Feature: API Endpoint untuk Delete Cadangan
1. Penambahan fungsi Delete pada file api/cadangan-api/controller/cadangan_controller.go
2. Penambahan fungsi Delete pada file api/cadangan-api/repository/cadangan_repository.go
> API Endpoint untuk Delete Cadangan

- public-web/src/components/Copyright.jsx
> Public-web - Add Page & Footer Link - Terms & Privacy (ReactJS)

- postgres/001_files_cdn.sql
- postgres/Dockerfile
> Create uploaded_files_cdn table

- postgres/005_kariah.sql
- postgres/Dockerfile
> Create kariah tables

- api/tabung-api/controller/kutipan_controller.go
- api/tabung-api/repository/kutipan_repository.go
- api/tabung-api/service/kutipan_service.go
curl --location --request DELETE 'localhost:8082/kutipan/9'
> [FEAT] delete endpoint for kutipan

- dashboard/src/service/tabung/KutipanApi.js
- dashboard/src/views/tabung/cetak/Cetak.js
logs :
2024-04-15 09:33:11 [GIN] 2024/04/15 - 01:33:11 | 204 |     107.708µs |    192.168.65.1 | OPTIONS  "/kutipan/12"
2024-04-15 09:33:11 {"level":"info","time":"2024-04-15T01:33:11Z","message":"delete kutipan by id : 12"}
2024-04-15 09:33:11 [GIN] 2024/04/15 - 01:33:11 | 200 |    8.798291ms |    192.168.65.1 | DELETE   "/kutipan/12"
2024-04-15 09:33:19 [GIN] 2024/04/15 - 01:33:19 | 204 |       44.75µs |    192.168.65.1 | OPTIONS  "/kutipan/16"
2024-04-15 09:33:19 {"level":"info","time":"2024-04-15T01:33:19Z","message":"delete kutipan by id : 16"}
2024-04-15 09:33:19 [GIN] 2024/04/15 - 01:33:19 | 200 |    4.606125ms |    192.168.65.1 | DELETE   "/kutipan/16"
> [FEAT] delete kutipan UI

- dashboard/src/components/header/AppHeaderDropdown.jsx
- dashboard/src/views/dashboard/Dashboard.jsx
- dashboard/src/views/tetapan/TetapanMasjid.jsx
Kena ada ID untuk update tetapan
> Bug fix for 250

- dashboard/package-lock.json
x pasti betul atau tidak cara nak update library tu, tapi sy just cd into dashboard and run npm update
> update library in dashboard

- dashboard/src/components/cadangan/CadanganEditor.jsx
- dashboard/src/service/cadangan/CadanganApi.js
> FEAT: button for delete cadangan

- apps/hub/package.json
- apps/hub/src/components/ContentPreview.tsx
- apps/hub/src/components/ContentSettingsDialog.tsx
- apps/hub/src/pages/admin/AdminDashboard.tsx
- apps/hub/src/pages/admin/DisplayManagement.tsx
- apps/hub/src/pages/content/CreateContent.tsx
- apps/tv-display/src/app/api/displays/[id]/config/route.ts
- apps/tv-display/src/app/api/displays/[id]/content/route.ts
- apps/tv-display/src/app/display/[id]/page.tsx
- apps/tv-display/src/components/ContentCarousel.tsx
- apps/tv-display/src/components/ContentViewer.tsx
- apps/tv-display/src/components/OfflineHandler.tsx
- apps/tv-display/src/components/PrayerTimesOverlay.tsx
- docs/DRAG-AND-DROP-CONTENT-ORDER.md
- packages/auth/src/index.tsx
- packages/shared-types/src/content-item.ts
- packages/shared-types/src/database.types.ts
- packages/shared-types/src/tv-display.ts
- packages/supabase-client/src/index.ts
- packages/supabase-client/src/services/display.ts
- pnpm-lock.yaml
- supabase/migrations/012_add_show_debug_info_to_displays.sql
- supabase/migrations/013_add_prayer_time_layout_settings.sql
- supabase/migrations/014_add_display_order_to_assignments.sql
- supabase/migrations/015_create_content_images_bucket.sql
- supabase/migrations/016_add_image_display_settings.sql
- supabase/migrations/017_add_content_specific_display_settings.sql
- Added image preview functionality in CreateContent component with clear image option.
- Implemented uploading state management during image uploads.
- Updated display settings in the API to include image display mode and background color.
- Enhanced content retrieval to include per-content settings like carousel duration and transition type.
- Modified ContentCarousel to utilize per-content display settings for transitions and image display.
- Updated ContentViewer to support different image display modes and background colors.
- Improved PrayerTimesOverlay alignment handling.
- Added new columns for image display settings in the database schema.
- Created migration scripts for new content-specific display settings and image display configurations.
> Content-type
